config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users

  # Pages
  root to: "pages#home", as: :home
  get "/search", to: "pages#search"

  # Referents
  get "/referents", to: "users#index"
  get "/referents/new", to: "users#new_referent", as: :new_referent
  patch "/referents/:id", to: "users#create_referent", as: :create_referent

  resources :users, only: [:show] do
    # get "/products", to: "user#products"
    resources :reviews, only: %i[new create edit update]
    get :details
  end

  # Products
  resources :products, shallow: true do
    resources :orders, except: [:index]
  end

  resources :reviews, only: [:destroy]

  # Orders
  patch "orders/:order_id/mark", to: "orders#close_order"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :photo
  has_many :reviews

  validates :first_name, :last_name, presence: true, length: { minimum: 2 }

  # El valor por defecto del role es 2: fashion_lover
  validates :role, presence: true
  enum :role, { admin: 0, referent: 1, fashion_lover: 2 }

  # validates :brand, presence: true # , on: :update
  validates :description, length: { maximum: 200 }

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @referents = User.referent
  end

  def new_referent
    @user = current_user
  end

  def create_referent
    user = User.find(params[:id])
    user.update_attribute(:role, 1)
    user.update(user_params)
    redirect_to home_path
  end

  def show
    @user = User.find(params[:id])
    @review = Review.new
  end

  def details
    if current_user.id == params[:user_id].to_i
      @products = current_user.products
      @orders = current_user.orders
    else
      redirect_to home_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:brand, :description)
  end
end

app/views/users/details.html.erb
<% if current_user.referent? %>
  <h2>My products</h2>
  <ol>
  <% @products.each do |product| %>
    <li><%= product.name %></li>
    <p><%= product.description %></p>
  <% end %>
  </ol>
<% else %>
  <h2>My orders</h2>
  <ol>
  <% @orders.each do |order| %>
    <li class="fw-bold"><%= order.product.name %></li>
    <p><%= order.payment %> | <%= order.delivery %></p>
  <% end %>
  </ol>
<% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row mt-2 gy-2">
<% @referents.each do |user| %>
    <%= render 'shared/row_referent', user: user %>
<% end %>
</div>

</div>

app/views/users/new_referent.html.erb
<div class="container">
<%= simple_form_for @user, url: create_referent_path(@user), method: :patch do |f| %>
  <div class="form-inputs">
    <%# Brand and description %>
    <%= f.input :brand %>
    <%= f.input :description, as: :text, :input_html => { rows: 5, cols: 10 }%>
    <%= f.submit "Become a Referent" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<% brands = [
  "https://images.unsplash.com/photo-1510897345173-4d938815feb4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1633409361618-c73427e4e206?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1525268771113-32d9e9021a97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1528840942-6d0562674ad6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1522125123931-9304d91a42ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=582&q=80",
  "https://images.unsplash.com/photo-1630750793287-fd38912df4d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=548&q=80",
  "https://images.unsplash.com/photo-1552985247-03b1fddb53d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=622&q=80"
]

products = [
  "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1594631770635-f2915410b410?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1617178388553-a9d022974a5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1601460588655-109bd38204db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1519167130418-c3640bd21b7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1630396592061-21f071e1a36c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80",
  "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80",
  "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=772&q=80",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
]
%>

<% if @user.referent? %>
  <div class="container">
    <div class="row mb-5">
      <div class="col-12">
        <h1 class="pt-5 font-t"><%= @user.brand %></h1>
      </div>
      <div class="col-md-12 col-lg-6 mt-3">
        <%= image_tag brands.sample, class: "col-12"%>
        <%# <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="col-md-12 col-lg-6 my-auto text-start">
        <h2 class="border-bottom mb-3 font-t">Sobre: <%= @user.brand %> </h2>
        <p class="font-p"><%= @user.description %></p>
      </div>
    </div>
  </div>

  <h2 class="text-center mb-3 font-t">Todos sus productos</h2>
  <div class="bg-page my-5 py-3">
    <div class="container">
      <div class="row mt-2 gy-2">
      <% @user.products.each do |product| %>
        <div class="col-6 col-md-3 my-4">
          <%= render 'shared/card_product', product: product %>
        </div>
      <% end %>
    </div>
  </div>
  </div>

  <div class = "container" class="col-md-6">
      <% if fashion_lover? && can_review?(@user) %>
        <div class="border border-dark p-3">
          <%= render 'shared/form_review', user: @user, review: @review %>
        </div>
      <% end %>
      <p class="card-text"> <h2 class="mt-5">Sus compradores dicen:</h2> <% @user.reviews.each do |review| %>
      <p class="card-text"><% review.rating.times do %> <i class="fa-solid fa-star"></i><% end %></p>
      <p class="list-group-item"><%= review.content %></p>

      <% if fashion_lover? && can_review?(@user) %>

      <small><p><%= link_to "Eliminar",
        review_path(review),
        data: {turbo_method: :delete, turbo_confirm: "Estas seguro?"}, class: "btn btn-sm btn-info"
      %></p></small></p>
      </p>
      <% end %>
    <% end %>
  </div>

<% elsif @user.fashion_lover? %>

<div class="container">
    <div class="row mb-5">
      <div class="col-12">
        <h1 class="border-bottom"><%= current_user.first_name %> <%= current_user.last_name %></h1>
      </div>
      <div class="col-md-12 col-lg-6 mt-3">
        <%= image_tag brands.sample, class: "col-12"%>
      </div>
      <div class="col-md-12 col-lg-6 my-auto text-start">
        <h2 class="border-bottom mb-3">Tu email: </h2>
        <p><%= current_user.email %></p>
      </div>
    </div>
    <h2 class="text-center mb-3">Mis ordenes</h2>
  <div class="row mt-2 gy-2">
  <% @user.orders.each do |order| %>
    <%= render 'shared/card_order', order: order %>
  <% end %>
  </div>

  </div>

<% else %>
  <p class="text-center text-danger font-t">Oh oh! No puedes acceder a este perfil!</p>
<% end %>
<<<<<<< HEAD


<div class = "container" class="col-md-6">
      <%= link_to "New Review", new_user_review_path(@user), class: "btn btn-lg btn-info"%>
        <p class="card-text"> <h5>All Reviews:</h5> <% @user.reviews.each do |review| %>
        <p class="card-text"><% review.rating.times do %> <i class="fa-solid fa-star"></i><% end %></p>
        <p class="list-group-item"><%= review.content %></p>
        <small><p><%= link_to "Delete",
          review_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-info"
        %></p></small>
      </p>
</p>
  <% end %>
</div>
=======
>>>>>>> 50992ad6546b5c3aef4948e5609f1381715fb35c