config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users

  # Pages
  root to: "pages#home", as: :home
  get "/search", to: "pages#search"

  # Referents
  get "/referents", to: "users#index"
  get "/referents/new", to: "users#new_referent", as: :new_referent
  patch "/referents/:id", to: "users#create_referent", as: :create_referent

  resources :users, only: [:show] do
    # get "/products", to: "user#products"
    resources :reviews, only: %i[new create edit update]
    get :details
  end

  # Products
  resources :products, shallow: true do
    resources :orders, except: [:index]
  end

  resources :reviews, only: [:destroy]

  # Orders
  patch "orders/:order_id/mark", to: "orders#close_order"
end

app/views/shared/_card_order.html.erb
<% brands = [
  "https://images.unsplash.com/photo-1510897345173-4d938815feb4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1633409361618-c73427e4e206?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1525268771113-32d9e9021a97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1528840942-6d0562674ad6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1522125123931-9304d91a42ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=582&q=80",
  "https://images.unsplash.com/photo-1630750793287-fd38912df4d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=548&q=80",
  "https://images.unsplash.com/photo-1552985247-03b1fddb53d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=622&q=80"
]
%>

<% products = [
  "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1594631770635-f2915410b410?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1617178388553-a9d022974a5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1601460588655-109bd38204db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1519167130418-c3640bd21b7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1630396592061-21f071e1a36c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80",
  "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80",
  "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=772&q=80",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
]


%>



<div class="col-6 col-md-4 my-4">
  <div class="card-brand shadow-sm">
    <%= image_tag products.sample, class: "card-img-top", height: 270 %>
    <div class="">
    <p><%= link_to order.product.name, order_path(order), class: "link-dark text-decoration-none" %></p>
      <div class="d-flex justify-content-between align-items-center py-2 px-1">
        <p class="m-0">Status: <%= "Open" if order.status %></p>
        <p class="m-0">Payment: <%= order.payment %></p>
        <%= link_to "View order", order_path(order), class: "btn btn-info p-0 px-1" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_product.html.erb
<% products = [
  "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1594631770635-f2915410b410?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1617178388553-a9d022974a5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1601460588655-109bd38204db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1519167130418-c3640bd21b7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1630396592061-21f071e1a36c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80",
  "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80",
  "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=772&q=80",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
]


%>


  <div class="shadow-sm">
    <div class="card"
     style="height: 180px;
     background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url( <%= image(product) %> )">
    </div>
    <div class="">
    <div class="my-2 fs-6">
      <%= link_to product.name.first(15) + "...", product_path(product), class: "text-dark text-decoration-none p-2 " %>
    </div>
      <div class="d-flex justify-content-between align-items-center py-2 px-1">
        <p class="m-0 ms-1 font-pb">$<%= product.price %></p>

        <% if referent_product?(product) %>
          <% unless product.available? %>
            <p class="m-0 ms-1 font-pb bg-primary px-2">Ordered</p>
          <% end %>
        <% end %>

        <% unless referent_user? %>
          <%= link_to "I want it!", new_product_order_path(product), class: "bg-info text-decoration-none text-dark px-2 py-1 rounded" %>
        <% end %>
      </div>
      <% if referent_product?(product) && !product.orders.empty? %>
        <%= link_to "View order details", order_path(product.orders.first.id), class: "text-light btn btn-dark m-1" %>
      <% end %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="row mt-4 py-5 bg-info">
  <div class="col-12">
    <p class="fw-bold text-center pt-3"> Made with 🧡 by Katapi </p>
  </div>
</div>

app/views/shared/_form_review.html.erb
<h2 class="my-4">Deja tu comentario</h2>
      <%= simple_form_for [user, review] do |f| %>
        <div class="field">
            <%= f.rich_text_area :content, as: :file %>
        </div>
        <%= f.input :rating, collection: (1..5).to_a, as: :radio_buttons, item_wrapper_class:"form-check-inline m-label" %>
        <%= f.submit "Enviar comentario", class: "btn btn-info" %>
      <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light sticky-top pb-2">
  <div class="container">
    <%= link_to "Referent", home_path, class: "navbar-brand fw-bold fs-4" %>


    <div class="d-flex justify-content-end align-items-center">
      <% if fashion_lover? %>
        <%= link_to "Conviertete en Referent", new_referent_path, class: "text-decoration-none text-secondary p-1 px-3 rounded-pill border"%>
      <% end %>

      <%= link_to "BUSCAR", search_path, class: "text-decoration-none text-dark mx-3 text-uppercase" %>

      <button class="navbar-toggler border-0 p-0 shadow-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class=""><i class="bi bi-person-circle text-dark fs-3"></i></span>
      </button>
    </div>


    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header py-3 px-3">
      <% if user_signed_in? %>
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><%= current_user.name %></h5>
      <% else %>
        <h5 class="offcanvas-title fs-6" id="offcanvasNavbarLabel">Bienvenido a Referent</h5>
      <% end %>
        <button type="button" class="btn-close shadow-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body py-1 px-3">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <% if user_signed_in? %>

            <%= link_to user_path(current_user), class: "nav-link active text-decoration-none" do %>
              <i class="bi bi-person-fill"></i>
              <span class="mx-2">Ver mi perfil</span>
            <% end %>


            <% if current_user.referent? %>
              <%= link_to new_product_path, class: "nav-link text-decoration-none" do %>
                <i class="bi bi-bag-heart"></i>
                <span class="mx-2">Agregar producto</span>
              <% end %>
            <% end %>

            <%= link_to edit_user_registration_path(current_user), class: "nav-link text-decoration-none" do %>
              <i class="bi bi-gear-fill"></i>
              <span class="mx-2">Ajustes de mi perfil</span>
            <% end %>

            <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link text-decoration-none" do %>
              <i class="bi bi-person-x-fill"></i>
              <span class="mx-2">Salir de mi cuenta</span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, class: "nav-link active text-decoration-none" do %>
              <i class="bi bi-person-fill"></i>
              <span class="mx-2">Entrar a mi cuenta</span>
            <% end %>
            <%= link_to new_user_registration_path, class: "nav-link text-decoration-none" do %>
              <i class="bi bi-person-heart"></i>
              <span class="mx-2">Registrarme</span>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar3.html.erb
<nav class="navbar navbar-expand-lg py-0 bg-light sticky-top">
  <div class="container px-0">
    <%= link_to "Referent", home_path, class: "navbar-brand fw-bold" %>

    <div class="d-flex align-items-center">
      <%= link_to search_path do %>
        <i class="bi bi-search mx-3 fs-5"></i>
      <% end %>

      <% if fashion_lover? %>
        <%= link_to "Become a Referent", new_referent_path %>
      <% end %>

      <div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <%= image_tag "https://st3.depositphotos.com/6672868/13701/v/600/depositphotos_137014128-stock-illustration-user-profile-icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <% if user_signed_in? %>
                <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>


                <% if current_user.referent? %>
                  <%= link_to "New product", new_product_path, class: "dropdown-item" %>
                <% end %>

                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
              </div>
              <% end %>

            </div>
          </li>
        </ul>
      </div>

    </div>
  </div>
</nav>

app/views/shared/_row_referent.html.erb
<% brands = [
  "https://images.unsplash.com/photo-1510897345173-4d938815feb4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1633409361618-c73427e4e206?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1525268771113-32d9e9021a97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1528840942-6d0562674ad6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1522125123931-9304d91a42ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=582&q=80",
  "https://images.unsplash.com/photo-1630750793287-fd38912df4d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=548&q=80",
  "https://images.unsplash.com/photo-1552985247-03b1fddb53d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=622&q=80"
]
%>


<div class="col-6 col-md-4">
  <div class="card-brand shadow-sm bg-color-beige">
    <%= image_tag brands.sample, class: "card-img-top", height: 270 %>
    <div class="border">
      <div class="d-flex justify-content-between align-items-center py-2 px-1">
        <p class="my-0 font-t"><%= user.brand %></p>
        <%= link_to "See more...", user_path(user), class: "bottom-orange font-pb" %>
      </div>
    </div>
  </div>
</div>