config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users

  # Pages
  root to: "pages#home", as: :home
  get "/search", to: "pages#search"

  # Referents
  get "/referents", to: "users#index"
  get "/referents/new", to: "users#new_referent", as: :new_referent
  patch "/referents/:id", to: "users#create_referent", as: :create_referent

  resources :users, only: [:show] do
    # get "/products", to: "user#products"
    resources :reviews, only: %i[new create edit update]
    get :details
  end

  # Products
  resources :products, shallow: true do
    resources :orders, except: [:index]
  end

  resources :reviews, only: [:destroy]

  # Orders
  patch "orders/:order_id/mark", to: "orders#close_order"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :status, :payment, :delivery, :user, :product, presence: true
  validates :status, inclusion: [true, false] # True - Open, False - Closed

  enum :payment, { cash: 0, 'Debit Card': 1, 'Credit Card': 2 }, scopes: false
  enum :delivery, { 'home delivery': 0, 'delivery point': 1 }, scopes: false

  scope :open, -> { where(status: true) } # Puedo usar Order.open
  scope :closed, -> { where(status: false) } # Puedo usar Order.closed

  def mark_as_closed!
    update_attribute(:status, false)
  end

  def closed?
    status == false
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_product, only: %i[new create change_status]

  def new
    redirect_to home_path if current_user.referent?
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
    redirect_to home_path unless current_user == @order.product.user || current_user == @order.user
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.product = @product
    @order.save
    if @order.save
      @product.mark_as_sold!
      redirect_to order_path(@order)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order = Order.update(order_params)
    redirect_to order_path(@order)
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  def close_order
    order = Order.find(params[:order_id])
    order.mark_as_closed!
    redirect_to order_path(order)
  end

  private

  def order_params
    params.require(:order).permit(:product_id, :current_user, :payment, :delivery, :status)
  end

  def status_params
    params.require(:order).permit(:status)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/views/orders/_image_product.html.erb
 <% if @product.photo.attached? %>
    <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill, rounded:4  %>
<% else %>
  <%= image_tag "https://previews.123rf.com/images/urfandadashov/urfandadashov1805/urfandadashov180500070/100957966-photo-not-available-icon-isolated-on-white-background-vector-illustration.jpg", height: 400, width: 400 %>
<% end %>

app/views/orders/edit.html.erb
 <hr>
  <div class="card-order col-10">
    <span> <i class="fa-solid fa-cart-shopping"></i>    1 order will be edited</span>
  </div>

  <div class="card-order col-10">

  <img width="500" src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" />
  <%= simple_form_for [@product, @order] do |f| %>
    <%= f.input :delivery, collection:  Order.deliveries.keys, prompt: "Choose delivery",  as: :radio_buttons, label: 'How do you want to receive the product?', error: 'Please select one option' %>
    <%= f.input :payment, collection: Order.payments.keys, prompt: "Choose", as: :radio_buttons, label: 'What will be the payment method?', error: 'Please select one option'%>
    <%= f.submit %>
  <% end %>
</div>

app/views/orders/new.html.erb
 <div class="container mx-auto my-3 bg-primary">

<div class="row col-12 p-5 rounded-4">
  <div class="col-6 mx-auto">


   <%= render 'orders/image_product' %>
   </div>
   <div class="col-6 mx-auto p-5">

    <%= simple_form_for [@product, @order] do |f| %>
      <%= f.input :delivery, collection:  Order.deliveries.keys, prompt: "Choose delivery",  as: :radio_buttons, label: 'How do you want to receive the product?', error: 'Please select one option' %>
      <%= f.input :payment, collection: Order.payments.keys, prompt: "Choose Payment Method", as: :radio_buttons, label: 'What will be the payment method?', error: 'Please select one option'%>

<!-- Button trigger modal -->
      <button type="button" class="btn btn-dark col-12" data-bs-toggle="modal" data-bs-target="#exampleModal">
       Create Order
      </button>
<!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><span> <i class="fa-solid fa-cart-shopping"></i>    1 order will be created</span></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="card-product-o">
          <%= render 'orders/image_product' %>
        <div class="card-product-infos-o">
          <h2> <%= @product.name %>  </h2>
          <p><strong> $ <%= @product.price %> </p></strong>
        </div>
      </div>
    </div>
        <div class="modal-footer">
          <%= f.submit "Create order", class: "btn btn-secondary" %>
          <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Back</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/orders/show.html copy.erb
<div class="row mx-auto my-5">
  <div class="col-12 d-flex">
<div class="card-category">
<% if @product.photo.attached? %>
  <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
<% else %>
<h1>articulo sin foto</h1>
<%= image_tag "https://previews.123rf.com/images/urfandadashov/urfandadashov1805/urfandadashov180500070/100957966-photo-not-available-icon-isolated-on-white-background-vector-illustration.jpg", height: 400, width: 400 %>
<% end %>

</div>

    <div class="info ms-5">
      <div class="row">
        <div class="col-12">
          <h1 class="border-bottom"><%= @product.name %></h1>
          <p class="brand"> <%= @product.brand %> </p>
          <p class="border-bottom"> <%= @product.description %> </p>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <p>Size: <%= @product.size %> </p>
          <p>Color: <%= @product.color %> </p>
          <p>Category: <%= @product.category %> </p>
          <p>Genre: <%= @product.genre %> </p>
        </div>

        <div class="col-6">
          <p>Price: <%= @product.price %> </p>

          <% unless referent_user? %>
            <%= link_to "I want it!", new_product_order_path(@product), class: "btn btn-info col-12" %>
          <% else %>
            <p class="text-danger">You need to log in with a Customer account!</p>
          <% end %>

        </div>
      </div>

      <% if referent_product?(@product) %>

        <%= link_to edit_product_path do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <% end %>

        <%=  link_to product_path(@product),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fa-solid fa-trash"></i>
        <% end %>

      <% end %>
    </div>
  </div>
  <div class="col-3 my-4">
    <%= link_to "Home", home_path, class: "btn btn-info" %>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Edit Product
    </button>

<!-- Modal -->
    <%= render 'products/modal_product' %>
  </div>
  </div>

app/views/orders/show.html.erb
<div class="container p-5 mt-5 bg-page">
<div class="row">
  <div class="col sm-12 col-8">
    <div class="card-order">
      <h2 class="d-inline p-2">Order Details</h2>
        <% if @order.status %>
      <span class="badge bg-success"> <%= "ORDER OPEN" %> </span>
      <% else %>
      <span class="badge bg-danger"><%= "ORDER COMPLETED" %> </span>
      <% end %>

    </div>

    <div class="card-order">
      <p>
      <%  @order.payment %> <i class="fa-regular fa-credit-card"></i> Your Payment Method:
      <strong><%= @order.payment %></strong></p>
    </div>

    <div class="card-order">
      <p> <%= image_tag "https://st3.depositphotos.com/6672868/13701/v/600/depositphotos_137014128-stock-illustration-user-profile-icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", 'aria-haspopup': true, 'aria-expanded': false %>
      Your Referent:  <strong><%= @order.product.brand %></strong></p>
    </div>

    <div class="card-order">
      <p> <%= image_tag "https://st3.depositphotos.com/6672868/13701/v/600/depositphotos_137014128-stock-illustration-user-profile-icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", 'aria-haspopup': true, 'aria-expanded': false %>
      Shopper:  <strong><%= @order.user.first_name%> <%= @order.user.last_name%></strong></p>
    </div>

    <div class="card-order">
      <%= link_to "Add review", user_path(@order.product.user) , class: "text-light btn btn-dark m-1" %>
    </div>


  <hr>

  <div class="card-product-o">
    <% if @order.product.photo.present? %>
      <%= cl_image_tag @order.product.photo.key %>
    <% else %>
    <%= image_tag "https://previews.123rf.com/images/urfandadashov/urfandadashov1805/urfandadashov180500070/100957966-photo-not-available-icon-isolated-on-white-background-vector-illustration.jpg", height: 400, width: 400 %>
    <% end %>

    <div class="card-product-infos-o">
      <h3> <%= @order.product.name %>  </h3>
      <h2> <%= @order.product.description %>  </h2>
      <p><strong>     $ <%= price = @order.product.price %> </p></strong>
    </div>
  </div>

    <hr>

    <% if referent_user? %>
      <%= link_to "Back", user_path(current_user), class:"btn btn-dark" %>
    <% else %>
      <%= link_to "Back to buy", products_path, class:"btn btn-dark" %>
    <% end %>

  </div>

  <div class="col-4">
    <% if referent_product?(@order.product) %>
      <% unless @order.status %>
      <button type='button' class="btn btn-info col-12 mb-3 rounded-pill" disabled> CLOSED ORDER</button>
      <% else %>
        <form action="<%=@order.id%>/mark" method="POST">
          <input type='hidden' name='_method' value='PATCH'/>
          <button type='submit' class="btn btn-info col-12 mb-3 rounded-pill">Mark order as dispatched</button>
        </form>
      <% end %>
    <% end %>

    <div class="card-order justify-content-center text-center">
      <div>
        <h3> Created at</h3>
        <p><%= @order.created_at.strftime('%A, %d de %B de %Y') %></p>
      </div>
    </div>


    <div class="card-order justify-content-center text-center">
      <div>
        <h3> Purchase detail </h3>
        <hr>
        <p> <%= @order.product.name %> $ <%= @order.product.price %> </p>
      </div>
    </div>

    <div class="card-order justify-content-center text-center">
      <div>
        <h3> Delivery detail </h3>
        <hr>
        <p> <%= @order.delivery %>  </p>
      </div>
    </div>

</div>
 <!-- <a class="btn btn-gradient" <%= link_to "Edit Order", edit_order_path %></a> -->
</div>