config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users

  # Pages
  root to: "pages#home", as: :home
  get "/search", to: "pages#search"

  # Referents
  get "/referents", to: "users#index"
  get "/referents/new", to: "users#new_referent", as: :new_referent
  patch "/referents/:id", to: "users#create_referent", as: :create_referent

  resources :users, only: [:show] do
    # get "/products", to: "user#products"
    resources :reviews, only: %i[new create edit update]
    get :details
  end

  # Products
  resources :products, shallow: true do
    resources :orders, except: [:index]
  end

  resources :reviews, only: [:destroy]

  # Orders
  patch "orders/:order_id/mark", to: "orders#close_order"
end

app/views/pages/_carousel_home.erb
<%# TEMPORAL %>
<% images = [
  "https://images.unsplash.com/photo-1575939238474-c8ada13b2724?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80",
  "https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "https://images.unsplash.com/photo-1543331707-30e9129663e0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=388&q=80",
  "https://images.unsplash.com/photo-1588731247530-4076fc99173e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80",
  "https://images.unsplash.com/photo-1505801066737-f25b349904b5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=873&q=80",
  "https://images.unsplash.com/photo-1508853363419-a9263d752c59?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
  "https://images.unsplash.com/photo-1468818461933-b1d79f62434e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
  ]

%>
<%# END TEMPORAL %>

<div id="carouselExampleControls" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="row g-0">
        <div class="col-12" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= images[0] %>); height: 500px">
        <div class="carousel-caption text-center">
          <h5 class="fs-1">Productos únicos</h5>
          <p class="fs-3">En <strong>Referent</strong> puedes encontrar productos de marcas locales</p>
        </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="row g-0">
        <div class="col-4" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= images[3] %>); height: 500px">
        </div>
        <div class="col-4" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= images[4] %>); height: 500px">
          <div class="carousel-caption text-center">
            <h2 class="fs-1">Encuentra tu referente de estilo</h2>
            <p class="fs-3">Y crea tu <strong> estilo propio!</strong></p>
          </div>
        </div>
        <div class="col-4" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= images[2] %>); height: 500px">
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="row g-0">
        <div class="col-12" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= images[7] %>); height: 500px">
          <div class="carousel-caption text-center">
            <h2 class="fs-1">¿Eres Diseñador?</h2>
            <p class="fs-3">¡Que esperas para convertirte en <strong> Referent</strong>!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/_referent.html.erb
<div class="bg-primary">
  <p>
    <strong>Name:</strong>
    <%= referent.searchable.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= referent.searchable.address %>
  </p>

</div>

app/views/pages/_search_form.html.erb
<div class="col-12 d-flex">
  <%# Search icon %>
  <div class="d-flex align-items-center justify-content-end">
    <i class="bi bi-search text-dark fs-5 p-2 border-bottom border-dark border-1"></i>
  </div>
  <%# End search icon %>

  <%# Formulario %>
  <div class="col-11">
    <%= form_with url: search_path, method: :get, class: "form-row", autocomplete: "off" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "shadow-none text-dark fs-5 p-2 px-3 form-control border-0 rounded-0 border-bottom border-dark border-1 w-100",
        placeholder: "SEARCH..."
      %>
      <%= submit_tag "Search", class: "btn d-none" %>
    <% end %>
  </div>
  <%# End formulario %>
</div>

<%# Small script for clean form %>
<script>
  document.getElementById("query").value = "";
</script>
<%# End script %>

app/views/pages/home.html.erb
<%# TEMPORAL %>
<% brands = [
  "https://images.unsplash.com/photo-1510897345173-4d938815feb4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1633409361618-c73427e4e206?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1525268771113-32d9e9021a97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1528840942-6d0562674ad6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1522125123931-9304d91a42ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=582&q=80",
  "https://images.unsplash.com/photo-1630750793287-fd38912df4d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=548&q=80",
  "https://images.unsplash.com/photo-1552985247-03b1fddb53d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=622&q=80"
]

products = [
  "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1594631770635-f2915410b410?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1617178388553-a9d022974a5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1601460588655-109bd38204db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1519167130418-c3640bd21b7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  "https://images.unsplash.com/photo-1630396592061-21f071e1a36c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80",
  "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80",
  "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=772&q=80",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
]

%>
<%# END TEMPORAL %>
<div class="container mt-5">
  <div class="row">
    <h2 class="fs-5 border-bottom border-success pb-2 text-success">
      Ultimos productos
    </h2>
  </div>

  <div class="row gy-2 pt-1">
    <% @products.first(12).each do |product| %>
    <div class="col-6 col-md-2 my-4">
      <%= render 'shared/card_product', product: product %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <h2 class="fs-6">
      <%= link_to products_path, class: "text-decoration-none text-dark" do %>
      Ver todos los productos <i class="bi bi-chevron-right"></i>
      <% end %>
    </h2>
  </div>

  <div class="row mt-5 py-5 border border-warning">
    <div class="col-5 text-center my-auto">
      <p>En <strong class="text-danger">Referent</strong> puedes encontrar productos de marcas locales emergentes. Cuando compras local ayudas al <strong>ambiente</strong>. Crea una cuenta ahora!</p>
      <%= link_to "Quiero ser un fashion lover", new_user_registration_path, class: "text-decoration-none bg-danger text-light p-2 rounded" %>
    </div>

    <div class="col-7 text-center">
        <div class="col-12" style="background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= "https://images.unsplash.com/photo-1578632292335-df3abbb0d586?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" %>); height: 500px">

        </div>
    </div>
  </div>
</div>



<div class="container">

<div class="mt-5 text-center pb-3">
  <h2 class="font-t"><%= link_to "Referents", referents_path %></h2>
</div>
<div class="row mt-2 g-1">
  <% num = 0 %>
  <% @referents.last(6).each do |referent| %>
    <div class="col-4 col-md-2">

    <div class="card border-0 rounded-0"
     style="height: 200px;
     background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= brands[num] %>)">
     <% num += 1 %>

    <%= link_to referent.brand, user_path(referent), class: "link-light text-decoration-none" %>

    </div>
    </div>


  <% end %>

  <div class="col-12 mt-5 d-flex justify-content-center">
   <p class="font-p"><%= link_to "See more Referents", referents_path %></p>
  </div>
</div>

app/views/pages/search.html.erb
<div class="row g-0">
  <%= render "search_form" %>
</div>

<div class="row">
  <div class="col-12 my-3">
    <p class="text-center text-secondary">
      <% if @query %>
        <%= @products.count %> results for "<%= @query %>"
      <% else %>
        All products
      <% end %>
    </p>
  </div>
</div>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-3">
      <%= render "shared/card_product", product: product %>
    </div>
  <% end %>
</div>